### ISSUE TITLE
Windows 10 disk image cannot be started in vitastor

### ISSUE THREAD

**Issue by kgdboc** [vitalif/vitastor#1]
Hi, I guess this is a bug related to reading small files.

Windows blue screen at startup：
![image](https://user-images.githubusercontent.com/63550743/112573528-73a51700-8e27-11eb-9444-6afd98f1703d.png)

Some windows 10 disk images can be started from vitastor. 

one node, one osd, vitastor version is 0.5.10

**Comment by kgdboc** [comment]
Sorry, This problem is because my windows do not have virtio driver installed

**Comment by vitalif** [comment]
Cool. I'm glad the issue was solved by itself :-)
By the way, I'm preparing another bunch of fixes which will be released as 0.5.11 and then there will be master with new features. So stay tuned :-)
