### ISSUE TITLE
[qemu] primary_write operation failed on OSD 1: retval=-32 (expected 131072), dropping connection

### ISSUE THREAD

**Issue by lnsyyj** [vitalif/vitastor#12]
When my virtual machine was turned on for about 24 hours, the following failed was reported in the qemu log.
```
primary_write operation failed on OSD 1: retval=-32 (expected 131072), dropping connection
```
I put the detailed log in: https://github.com/lnsyyj/vitastor-log/blob/main/qemu-ubuntu18.04.log

**Comment by vitalif** [comment]
It's not a problem, it's just a "repeat" indication. -32 is -EPIPE, it's used to report temporary failures or connection drops :-)
