### ISSUE TITLE
qemu upload disk image error: Co-routine re-entered recursively

### ISSUE THREAD

**Issue by kgdboc** [vitalif/vitastor#2]
I installed vitastor 0.5.11 and qemu from yum using CentOS 7.9, and an error was reported when I executed the following command:

[root@c7-dev ~]# qemu-img convert -f qcow2 -p /o/disk/f33.qcow2 -O raw 'vitastor:etcd_host=192.168.15.11\\:2379/v3:pool=1:inode=2:size=13098811392'
Co-routine re-entered recursively
Aborted
[root@c7-dev ~]# 

fio can run normally.

**Comment by vitalif** [comment]
Hi. Yeah it seems it's broken after the cluster_client rework. I'll check it and add it to tests.

**Comment by vitalif** [comment]
Hi, fixed, check out 0.5.12

**Comment by vitalif** [comment]
Huh. Ok, I found one more case failing in 0.5.11-0.5.12. I'll probably fix it and re-upload 0.5.12 because it's just too funny)

**Comment by vitalif** [comment]
Ok. Now you can check it out :)
