### ISSUE TITLE
In the v0.6.2 version, after stopping one osd, the running virtual machine will become freezes.

### ISSUE THREAD

**Issue by kgdboc** [vitalif/vitastor#3]
Hi, this is a bug that only exists in the new version, when I tested it with v0.5.10, there was no such bug.

I use 3 nodes, 2 osd per node, killing any osd process will cause this bug.

**Comment by vitalif** [comment]
Hi, yeah, I've just fixed this bug in master, it reproduces when immediate_commit != all. I'll build packages with the fix tomorrow... I'm wondering if I should release 0.6.3 with just this fix and 0.7.0 with RDMA and client performance improvements or just put everything into 0.6.3 :)

**Comment by vitalif** [comment]
Fixed, try 0.6.3. It also has RDMA support :-)
