### ISSUE TITLE
vitastor etcd, issue with connections?

### ISSUE THREAD

**Issue by legendary-cookie** [vitalif/vitastor#60]
Sample output from etcd, obtained by running systemc

Feb 18 18:50:42 pvecn5 etcd[7406]: {"level":"warn","ts":"2024-02-18T18:50:42.8278+0100","caller":"embed/serve.go:331","msg":"error reading websocket message:websocket: close 1006 (abnormal closure): unexpected EOF"}

Is this normal behaviour?

**Comment by vitalif** [comment]
It doesn't affect anything, I see it myself all the time)) you can try to set `etcd_ws_keepalive_interval` for example to 15 and see it if will go away. But I doubt it will :-) I don't know what causes these errors.

**Comment by legendary-cookie** [comment]
Alright. I‘ll close this then.
