### ISSUE TITLE
permanent IO delay/IO waits in vitastor cluster

### ISSUE THREAD

**Issue by getcom** [vitalif/vitastor#68]
Hello,

we are running an 8 machine proxmox cluster with vitastor as a backend for VM storage. We use 100 gbit/s infiniband connections between the nodes. This is our first time running vitastor, so we cannot reference other values. We currently only run a few VMs on each node, in total about 22. The IO delay shown in proxmox is comparativly high (about 8% on this node, on all nodes ranging from 6%-8% each. IO delay is the io wait of the whole system)
![grafik](https://github.com/vitalif/vitastor/assets/1664110/6b5266c4-3f5c-4236-aa10-dd808cb4eeef)

Each node has a two EPYC 7451 (96 threads in total) CPUs, and as mentioned above 100 gbit infiniband.

Is this normal behaviour with vitastor? Is it because we have an otherwise really low CPU system load?

**Comment by getcom** [comment]
We have 6 OSDs per node. Intel Datacenter SSDs with 3.84TB
The VM storage pool is configured like this:
```
{"2": {"failure_domain": "host", "name": "ecpool", "parity_chunks": 2, "pg_count": 1024, "pg_minsize": 2, "pg_size": 4, "scheme": "ec"}}
```

**Comment by vitalif** [comment]
Hi. Is this iowait%? If yes then it's fine, it represents a recent change in how Linux kernel calculates iowait for the io_uring I/O thread. Now a thread running in io_uring is always counted as 100% iowait.

So... this is a kernel feature, not a bug :)

Here are the discussions:
https://bbs.archlinux.org/viewtopic.php?id=287343
https://bugzilla.kernel.org/show_bug.cgi?id=217700
https://lore.kernel.org/lkml/538065ee-4130-6a00-dcc8-f69fbc7d7ba0@kernel.dk/

Jens Axboe:
Just read the first one, but this is very much expected. It's now just correctly reflecting that one thread is waiting on IO. IO wait being 100% doesn't mean that one core is running 100% of the time, it just means it's WAITING on IO 100% of the time.

**Comment by getcom** [comment]
@vitalif 
Thank you for your fast response. Yes, it is the iowait of an example PVE host. It looks similar on all eight nodes.
This is new for me.

**Comment by getcom** [comment]
Clarified and closed
