### ISSUE TITLE
Does vitastor have data read and write demo?

### ISSUE THREAD

**Issue by lnsyyj** [vitalif/vitastor#8]
Hi @vitastor,
There is a question, think about you for advice. Does vitastor have a demo for reading and writing? I saw src\test_cluster_client.cpp, but it seems that it does not write data to the real cluster. Can you provide a complete demo for reading and writing?

**Comment by vitalif** [comment]
Do you want programmatic r/w support? No, there is no demo, but now there is a simplified C wrapper library vitastor_c.h. You can check out how to use it in fio_cluster.cpp

**Comment by lnsyyj** [comment]
Thank you, I have tested the read-write interface.
https://github.com/lnsyyj/vitastor/blob/wip-test-write/src/test_write.cpp
